---
title: "Portfolio Optimization"
author: "Yang Wu"
date: "9/13/2021"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(comment = NA)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.align = "center")
library(reticulate)
reticulate::use_condaenv(
  condaenv = "python_for_finance",
  conda = "/Users/kenwu/opt/anaconda3/envs/python_for_finance",
  required = TRUE
)
```

## Load libraries

We need the following Python modules:

```{python}
import numpy as np
import pandas as pd
from pandas_datareader import data as web
import matplotlib.pyplot as plt 
```

## Data

We pick 21 different assets for the analysis with exposure to all of the GICS sectors— energy, materials, industrials, utilities, healthcare, financials, consumer discretionary, consumer staples, information technology, communication services, and real estate. The start date is `2011-09-13` and the end date is by default today's data, which is `r Sys.Date()`.

```{python}
# Create a list of symbols
symbols = [
  "XOM", "SHW", "JPM", "AEP", "UNH", "AMZN", "AAPL", "KO",
  "GOOGL", "GE", "SBUX", "PFE", "MSFT", "BA", "AMT",
  "DD", "JNJ", "TSN", "CVX", "SLG", "SPY"
]
# Initialize data container
asset_data = pd.DataFrame()
# For loop to get data from Yahoo finance
for sym in symbols:
  # Each run of the loop returns a pandas data frame
  asset_data[sym] = web.DataReader(
    name = sym, 
    data_source = 'yahoo',
    start = '2011-09-13'
    # Use [ to extract as pandas series
    )['Adj Close']
# Set column indices
asset_data.columns = symbols
# Examine the first 5 rows
asset_data.head(n = 5)
```

Next, we find the simple daily returns for each of the assets using the `pct_change()` function. We use simple returns since they have the property of being asset-additive. 

```{python}
# Compute daily simple returns
daily_returns = (
  asset_data.pct_change()
            .dropna(
              # Drop the first row since we have NaN's
              axis = 0,
              how = 'any',
              inplace = False
              )
)
# Examine the last 5 rows
daily_returns.tail(n = 5)
```

Let us annualize the daily returns over the 10-year period from `2011-9-13` to `r Sys.Date()`. We assume the number of trading days in a year is $365.25 \text{(days on average per year)} \times \frac{5}{7} \text{(proportion work days per week)} - 6 \text{(weekday holidays)} - 3\times\frac{5}{7} \text{(fixed date holidays)} = 252.75 \approx 253$:

```{python}
daily_returns.mean() * 253
```

As can be seen, there is significant differences in the annualized performance between these assets. Amazon dominated over the period with an annualized rate of return of $32.5\%$. Exxon Mobil Corporation, on the other hand, is at the bottom of the rankings based on this sample, recording an annualized rate of return of $4.5\%$ over the period. The annualized variance-covariance matrix of the returns can be computed using built-in `pandas` method `cov`:

```{python}
daily_returns.cov() * 253
```










